// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;
using WebApi.Models;

namespace WebApi.Models
{
    public partial class ELSLogs
    {
        private string _elsIpaddress;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ElsIpaddress
        {
            get { return this._elsIpaddress; }
            set { this._elsIpaddress = value; }
        }
        
        private string _elsRequest;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ElsRequest
        {
            get { return this._elsRequest; }
            set { this._elsRequest = value; }
        }
        
        private int? _elsResponse;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ElsResponse
        {
            get { return this._elsResponse; }
            set { this._elsResponse = value; }
        }
        
        private ElsUserInfromation _elsUser;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ElsUserInfromation ElsUser
        {
            get { return this._elsUser; }
            set { this._elsUser = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ELSLogs class.
        /// </summary>
        public ELSLogs()
        {
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ELSLogs
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.ElsIpaddress != null)
            {
                outputObject["ElsIpaddress"] = this.ElsIpaddress;
            }
            if (this.ElsRequest != null)
            {
                outputObject["ElsRequest"] = this.ElsRequest;
            }
            if (this.ElsResponse != null)
            {
                outputObject["ElsResponse"] = this.ElsResponse.Value;
            }
            if (this.ElsUser != null)
            {
                outputObject["ElsUser"] = this.ElsUser.SerializeJson(null);
            }
            return outputObject;
        }
    }
}
